# Generated by Django 3.2.8 on 2021-11-22 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houseplants_api', '0005_auto_20211017_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_date', models.DateField(auto_now_add=True)),
                ('next_suggested_date', models.DateField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houseplants_api.plant')),
            ],
        ),
    ]
